### ISSUE TITLE
Light mode exists

### ISSUE THREAD

**Issue by YouHaveTrouble** [Encode42/awesome-yatopia#1]
I petition to remove light theme completely.

- "Who needs that?" - light mode hater
- "Why would anyone do that to themselves?" - dark mode enthusiast

**Comment by Encode42** [comment]
I agree that light mode is rarely needed, but I have decided to make it easier for users to select and retain light mode in f167ecbbb183005e8ea4658dc0d4590068a49c12 just to spite you

:)
